### ISSUE TITLE
[Access Denied] edgeHub directory maping is not working while setting up using container create options

### ISSUE THREAD

**Issue by niravjprabtani** [Azure/iotedge-eflow#112]
**Describe the bug**
Permission issue while setting up host and container volume mapping for edgeHub

**Expected behavior**
It should work without permission issue or at least there should be a way to provide permissions for it

![image](https://user-images.githubusercontent.com/49067519/149724274-d2cc0cab-981b-4c97-90bb-54e9e59c117b.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 Enterprise LTSC
 - Version:  1809 (OS Build 17763.2366)
 
**Additional context**
edgeHub is working fine without storage mapping with host but it stopped working with mapping. 
How to provide access to a particular directory using EFLOW?

I have tried all possible directories like /home/iotedge-user, /temp, /var/tmp ...

**edgeHub**
```
2022-01-17 07:12:00  Starting Edge Hub
2022-01-17 07:12:00.570 +00:00 Edge Hub Main()
<6> 2022-01-17 07:12:02.155 +00:00 [INF] - Installing certificates [CN=iotedged workload ca:04/17/2022 05:47:04],[CN=Test Edge Device CA:04/17/2022 05:47:04],[CN=Test Edge Owner CA:04/17/2022 05:47:04] to Root
<6> 2022-01-17 07:12:02.218 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:04/17/2022 05:47:04] to Root
<6> 2022-01-17 07:12:02.232 +00:00 [INF] - Enabling SSL protocols: Tls, Tls11, Tls12
Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the path '/var/tmp/storage/edgeHub' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '/var/tmp/storage/edgeHub' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.GetOrCreateDirectoryPath(String baseDirectoryPath, String directoryName) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 307
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.GetStoreAndForwardConfiguration() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 255
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.Register(ContainerBuilder builder) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 86
   at Microsoft.Azure.Devices.Edge.Hub.Service.Startup.BuildContainer(IServiceCollection services) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Startup.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Service.Startup.ConfigureServices(IServiceCollection services) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Startup.cs:line 44
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Hosting.Initialize(IConfigurationRoot configuration, X509Certificate2 serverCertificate, IDependencyManager dependencyManager, Boolean clientCertAuthEnabled, SslProtocols sslProtocols) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Hosting.cs:line 80
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 62
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 33
2022-01-17 07:12:17  Starting Edge Hub
2022-01-17 07:12:17.629 +00:00 Edge Hub Main()
<6> 2022-01-17 07:12:18.933 +00:00 [INF] - Installing certificates [CN=iotedged workload ca:04/17/2022 05:47:04],[CN=Test Edge Device CA:04/17/2022 05:47:04],[CN=Test Edge Owner CA:04/17/2022 05:47:04] to Root
<6> 2022-01-17 07:12:18.994 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:04/17/2022 05:47:04] to Root
<6> 2022-01-17 07:12:18.998 +00:00 [INF] - Enabling SSL protocols: Tls, Tls11, Tls12
Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the path '/var/tmp/storage/edgeHub' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '/var/tmp/storage/edgeHub' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.GetOrCreateDirectoryPath(String baseDirectoryPath, String directoryName) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 307
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.GetStoreAndForwardConfiguration() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 255
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.Register(ContainerBuilder builder) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 86
   at Microsoft.Azure.Devices.Edge.Hub.Service.Startup.BuildContainer(IServiceCollection services) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Startup.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Service.Startup.ConfigureServices(IServiceCollection services) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Startup.cs:line 44
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Hosting.Initialize(IConfigurationRoot configuration, X509Certificate2 serverCertificate, IDependencyManager dependencyManager, Boolean clientCertAuthEnabled, SslProtocols sslProtocols) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Hosting.cs:line 80
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 62
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 33
2022-01-17 07:12:44  Starting Edge Hub
2022-01-17 07:12:44.432 +00:00 Edge Hub Main()
<6> 2022-01-17 07:12:46.093 +00:00 [INF] - Installing certificates [CN=iotedged workload ca:04/17/2022 05:47:04],[CN=Test Edge Device CA:04/17/2022 05:47:04],[CN=Test Edge Owner CA:04/17/2022 05:47:04] to Root
<6> 2022-01-17 07:12:46.184 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:04/17/2022 05:47:04] to Root
<6> 2022-01-17 07:12:46.196 +00:00 [INF] - Enabling SSL protocols: Tls, Tls11, Tls12
Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the path '/var/tmp/storage/edgeHub' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path '/var/tmp/storage/edgeHub' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.GetOrCreateDirectoryPath(String baseDirectoryPath, String directoryName) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 307
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.GetStoreAndForwardConfiguration() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 255
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.Register(ContainerBuilder builder) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs:line 86
   at Microsoft.Azure.Devices.Edge.Hub.Service.Startup.BuildContainer(IServiceCollection services) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Startup.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Service.Startup.ConfigureServices(IServiceCollection services) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Startup.cs:line 44
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Hosting.Initialize(IConfigurationRoot configuration, X509Certificate2 serverCertificate, IDependencyManager dependencyManager, Boolean clientCertAuthEnabled, SslProtocols sslProtocols) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Hosting.cs:line 80
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 62
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 33
```

**Comment by fcabrera23** [comment]
Hi @niravjprabtani,

Before mapping the folder, make sure to create the folder inside the EFLOW VM, and assign the appropriate ownership (iotedge user) and permissions.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @niravjprabtani,

Manual creation and setting the appropriate ownership permissions is the recommended way. However, automatic creation also works, as long as the iotedge user has writing permissions over the folder that the new folder wants to be created. 

Thanks,
Francisco
