### ISSUE TITLE
LBS disconnected because of unrecognized LnsMessageType

### ISSUE THREAD

**Issue by adcoly** [Azure/iotedge-eflow#157]
**Describe the bug**
Everytime my LBS send a discover message and connect to the LNS, it is disconnected due to a message unrecognized by the LNS

**Windows Host OS (please complete the following information):**
 - Edition: Windows Server 2019 Datacenter
 - Version: 17763.2458
 - Virtual Machine: VM Ware virtual machine
 
**Additional context**
LoraWanNetworkSrvModule logs (debug level):
`WebSocket connection from <IP_Adsress> established
<GatewayId> Received 'version' message for station '2.0.3(brwodu/debugn)' with package '1.0.0'.
<GatewayId> using edgeHub local queue
<GatewayId> updating twin
<GatewayId> twin updated
<GatewayId> using edgeHub local queue
<GatewayId> getting device twin
<GatewayId> done getting device twin
An exception occurred while processing requests: System.FormatException: Could not parse alarm as a valid LnsMessageType.
   at LoRaWan.NetworkServer.BasicsStation.LnsMessageTypeParser.ParseAndValidate(String s, Nullable`1 expectedType) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/LnsMessageTypeParser.cs:line 29
   at LoRaWan.NetworkServer.BasicsStation.JsonHandlers.LnsData.<>c__DisplayClass1_0.<MessageTypeProperty>b__0(String t) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/JsonHandlers/LnsData.cs:line 17
   at LoRaWan.NetworkServer.JsonReader.<>c__DisplayClass17_0`2.<Select>b__0(Utf8JsonReader& rdr) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JsonReader.cs:line 317
   at LoRaWan.NetworkServer.JsonReader.DelegatingJsonReader`1.Read(Utf8JsonReader& reader) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JsonReader.cs:line 328
   at LoRaWan.NetworkServer.JsonReader.<Object>g__ReadPropertyValue|14_1[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,TResult,TValue](IJsonProperty`1 property, Utf8JsonReader& reader, ValueTuple`2& value) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JsonReader.cs:line 231
   at LoRaWan.NetworkServer.JsonReader.<>c__DisplayClass14_0`17.<Object>b__0(Utf8JsonReader& reader) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JsonReader.cs:line 197
   at LoRaWan.NetworkServer.JsonReader.DelegatingJsonReader`1.Read(Utf8JsonReader& reader) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JsonReader.cs:line 328
   at LoRaWan.NetworkServer.JsonReader.Read[T](IJsonReader`1 reader, ReadOnlySpan`1 utf8JsonTextBytes) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JsonReader.cs:line 36
   at LoRaWan.NetworkServer.JsonReader.Read[T](IJsonReader`1 reader, String json) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JsonReader.cs:line 29
   at LoRaWan.NetworkServer.BasicsStation.Processors.LnsProtocolMessageProcessor.HandleDataMessageAsync(StationEui stationEui, IWebSocketWriterHandle`1 socket, String json, CancellationToken cancellationToken) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/Processors/LnsProtocolMessageProcessor.cs:line 190
   at LoRaWan.NetworkServer.BasicsStation.Processors.LnsProtocolMessageProcessor.InternalHandleDataAsync(RouteValueDictionary routeValues, WebSocket socket, CancellationToken cancellationToken) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/Processors/LnsProtocolMessageProcessor.cs:line 166
   at LoRaWan.NetworkServer.BasicsStation.Processors.LnsProtocolMessageProcessor.InternalHandleDataAsync(RouteValueDictionary routeValues, WebSocket socket, CancellationToken cancellationToken) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/Processors/LnsProtocolMessageProcessor.cs:line 177
   at LoRaWan.NetworkServer.BasicsStation.Processors.LnsProtocolMessageProcessor.ProcessIncomingRequestAsync(HttpContext httpContext, Func`4 handler, CancellationToken cancellationToken) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/Processors/LnsProtocolMessageProcessor.cs:line 77.
Connection id "0HMIASQ3N0JEO", Request id "0HMIASQ3N0JEO:00000002": An unhandled exception was thrown by the application.
Executed endpoint '/router-data/{routerId:required} HTTP: GET'
Request finished HTTP/1.1 GET https://.../router-data/... - - - 101 - - 5846.7286ms
Connection id "0HMIASQ3N0JEO" disconnecting.`

**Comment by fcabrera23** [comment]
Hi @adcoly,

Thanks for sharing the information above. The issue described seems to be related to [Azure IoT Edge LoRaWAN Starter Kit](https://github.com/Azure/iotedge-lorawan-starterkit) and not to EFLOW. I tried transferring the issue to that repo, but I couldn't do it. So I'd suggest opening the issue in their repo; if this is EFLOW specific, the team will contact us internally and work together to solve it. 

Thanks,
Francisco
