### ISSUE TITLE
Connecting to serial port over network throws an exception

### ISSUE THREAD

**Issue by yongkur** [Azure/iotedge-eflow#201]
**Describe the bug**
Following example Connecting to serial port over network, This does not map exactly to .NET6

**To Reproduce**
1. Compile the following code:

```
using System.IO.Ports;

 var sp = new SerialPort("/dev/ttyVirtS1", 9600)
            {
                DataBits = 8,
                Parity = Parity.None,
                StopBits = StopBits.One,
                WriteTimeout = TimeSpan.FromSeconds(3).Seconds,
                ReadTimeout = TimeSpan.FromMilliseconds(30).Seconds,
                Handshake = Handshake.None,
                DtrEnable = false,
                RtsEnable= false,
                DiscardNull= false,
                ParityReplace=0,
            };

try
{
    sp.Open();
  
}
catch (Exception e) { Console.WriteLine(e); }


 sp = new SerialPort("/dev/ttyVirtS1", 9600)
            {
                DataBits = 8,
                Parity = Parity.None,
                StopBits = StopBits.One,
                WriteTimeout = TimeSpan.FromSeconds(3).Seconds,
                ReadTimeout = TimeSpan.FromMilliseconds(30).Seconds,
                Handshake = Handshake.None,
                DtrEnable = true,
                RtsEnable= false,
                DiscardNull= false
            };

try
{
    sp.Open();
  
}
catch (Exception e) { Console.WriteLine(e); }

```

2. Compile command  `dotnet publish "test.csproj"  -c Release --self-contained true --runtime linux-x64 -o out`

3. Use com2com project as mentioned in example
`com2tcp-rfc2217.bat \\.\COM1 5002`

4.  Use socat to open a PTY
`sudo socat pty,link=/dev/ttyVirtS1,raw,user=iotedge-user,group=dialout,mode=660 tcp:172.18.246.137:5002`

5. Copy the build test case into Eflow, Run the test case
6. See error
`System.IO.IOException: Inappropriate ioctl for device
   at System.IO.Ports.SerialStream.set_DtrEnable(Boolean value)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at serialtester.Program.Main(String[] args) 

System.IO.IOException: Inappropriate ioctl for device
   at System.IO.Ports.SerialStream.set_DtrEnable(Boolean value)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at serialtester.Program.Main(String[] args) 
`

**Expected behavior**
able to open a pseudo-tty

**Windows Host OS (please complete the following information):**
 - Edition: Eflow 
 - Version: Iotedge 1.1 ,iotedge 1.4
 - Virtual Machine: Eflow 
 
**Additional context**
Tool like modpoll able to get data from the  /dev/ttyVirtS1

**Comment by fcabrera23** [comment]
Hi @yongkur,

Thanks for the information. Before trying to debug the SDK, could you please check that the binding is actually working?
From inside the EFLOW VM, please run the following command:

 `sudo docker run -t -i -v /dev/ttyVirtS1:/dev/ttyVirtS1--privileged  ubuntu bash`.

Once inside the container, check the incoming messages:

 `cat /dev/ttyVirtS1`.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @yongkur,

Were you able to check the commands shared above? Do you still need our help?

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Closing due to inactivity
