### ISSUE TITLE
Error associating _mediaCapture.StartPreviewAsync()

### ISSUE THREAD

**Issue by jbsterasawas** [Azure/iotedge-eflow#26]
**Describe the bug**
When I try to run custom vision UWP application, the same error always happen around _mediaCapture.StartPreviewAsync().
My Windows 10 environment is "Windows 10 version Dev (OS Build 21376.1)".

**To Reproduce**
1. Debug on Visual Studio or run UWP application.

**Expected behavior**
Preview of video capture is shown.

**Screenshots**
The error message is following.

> System.Exception
  HResult=0xC00D5212
  Message=No suitable transform was found to encode or decode.
No suitable transform was found to encode or decode.
  Source=System.Private.CoreLib
  Stack Trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DeviceCustomVisionUWPApp.MainPage.<StartPreviewAsync>d__42.MoveNext() in C:\customvision\DeviceCustomVisionUWPApp\MainPage.xaml.cs:line 435
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DeviceCustomVisionUWPApp.MainPage.<InitializeCameraAsync>d__40.MoveNext() in C:\customvision-test\customvision\DeviceCustomVisionUWPApp\MainPage.xaml.cs:line 403
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DeviceCustomVisionUWPApp.MainPage.<>c__DisplayClass47_0.<<SetUpBasedOnStateAsync>b__0>d.MoveNext() in C:\customvision\DeviceCustomVisionUWPApp\MainPage.xaml.cs:line 607
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DeviceCustomVisionUWPApp.MainPage.<SetUpBasedOnStateAsync>d__47.MoveNext() in C:\customvision\DeviceCustomVisionUWPApp\MainPage.xaml.cs:line 618
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DeviceCustomVisionUWPApp.MainPage.<Window_VisibilityChanged>d__36.MoveNext() in C:\customvision\DeviceCustomVisionUWPApp\MainPage.xaml.cs:line 289

**Windows Host OS (please complete the following information):**
 - Edition: [Windows 10 Pro]
 - Version: [Build 21376.1]
 
**Additional context**
Other functions included in application, such as connecting to IoT Edge device, work correctly.

**Comment by fcabrera23** [comment]
Hi @jbsterasawas,

Thanks for all the detailed information. It seems that you are having some kind of problem with the camera options.  It would be useful if we could get more details

1) Are you using a USB camera or the laptop'camera?
2) Did you accepted the necessary access permissions when running the sample code?
3) Could you please try running the program on Admin mode?

Also, it looks like the Package.appxmanifest file is missing the device capability that gives it access to the Webcam. Could you please check the following docs and check everything is ok
 - [App capability declarations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
 - [How to specify device capabilities in a package manifest - Windows UWP applications](
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-device-capabilities-in-a-package-manifest)

**Comment by jbsterasawas** [comment]
Hi @fcabrera23 

Thank you for replying. 

1. Are you using a USB camera or the laptop'camera?
→I tried with both USB camera and the laptop' camera, and both of them got the same error.
2. Did you accepted the necessary access permissions when running the sample code?
→I accepted "camera access" and "microphone access" when running the sample code.
3. Could you please try running the program on Admin mode?
→I opened project with Visual Studio on Admin mode, but the same error occured.

The Package.appxmanifest file includes following capabilities.

> <Capabilities>
    <Capability Name="internetClient" />
    <uap:Capability Name="picturesLibrary"/>
    <Capability Name="privateNetworkClientServer"/>
    <Capability Name="codeGeneration"/>
    <iot:Capability Name="systemManagement"/>
    <DeviceCapability Name="webcam"/>
    <DeviceCapability Name="microphone"/>
  </Capabilities>

Is there any other device capability required?

**Comment by fcabrera23** [comment]
Hi @jbsterasawas,

The issue seems to be related to Windows.Media.Capture API. Could you please try downloading the [library sample app](https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/cameramanualcontrols/)  and see if you get the same error?

If so, we will have to create an issue to the corresponding team. Also, I'll encourage you to search for similar issues in the [Windows Universal Samples](https://github.com/microsoft/Windows-universal-samples/issues) repo.

**Comment by jbsterasawas** [comment]
Hi @fcabrera23,

I downloaded sample app and got the same error as below.

> System.Runtime.InteropServices.COMException
  HResult=0xC00D5212
  Message=No suitable transform was found to encode or decode.
No suitable transform was found to encode or decode.
  Source=System.Private.CoreLib
  Stack Trace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CameraManualControls.MainPage.<StartPreviewAsync>d__62.MoveNext() in C:\test\Manual_camera_controls_sample\cs\MainPage.xaml.cs:line 374
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CameraManualControls.MainPage.<InitializeCameraAsync>d__61.MoveNext() in C:\test\Manual_camera_controls_sample\cs\MainPage.xaml.cs:line 349
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CameraManualControls.MainPage.<OnNavigatedTo>d__49.MoveNext() in C:\test\Manual_camera_controls_sample\cs\MainPage.xaml.cs:line 130
  This exception was originally thrown at this call stack: 
    [External Code]
    CameraManualControls.MainPage.StartPreviewAsync() (in MainPage.xaml.cs)
    [External Code]
    CameraManualControls.MainPage.InitializeCameraAsync() (in MainPage.xaml.cs)
    [External Code]
    CameraManualControls.MainPage.OnNavigatedTo(Windows.UI.Xaml.Navigation.NavigationEventArgs) (in MainPage.xaml.cs)

I will also keep searching for similar issue.

**Comment by fcabrera23** [comment]
Hi @jbsterasawas,

Thanks for trying that. The issue is definitely with Windows Media Capture API. Please open a new issue on [Windows-universal-samples repo](https://github.com/microsoft/Windows-universal-samples/issues). 

Thanks,
Francisco
