### ISSUE TITLE
Module not running after reboot

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#46]
**Describe the bug**
AFter rebooting our device (hardwired into network). (Device was provisioned with DpsTpm) we installed a module on it and were seeing the following log output:
nhandled exception. System.AggregateException: One or more errors occurred. (Error calling SignAsync: Module not found
        caused by: Signing error occurred.
        caused by: An error occurred in the key store.
        caused by: HSM failure
        caused by: HSM API failure occurred: 478, StatusCode: 404)
 ---> Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling SignAsync: Module not found
        caused by: Signing error occurred.
        caused by: An error occurred in the key store.
        caused by: HSM failure
        caused by: HSM API failure occurred: 478, StatusCode: 404
   at Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmSignatureProvider.SignAsync(String moduleId, String generationId, String data)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.ModuleAuthenticationWithHsm.SafeCreateNewToken(String iotHub, Int32 suggestedTimeToLive)
   at Microsoft.Azure.Devices.Client.AuthenticationWithTokenRefresh.GetTokenAsync(String iotHub)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ConnectAsync(IChannelHandlerContext context)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass38_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at LogModule.ModuleClientHandler.Init() in /app/LogModule/ModuleClientHandler.cs:line 31
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
did a Stop-EflowVm and Start-eflowvm and things started working.   

This is on a windows 10 IOT Enterprise 1809 OS with the latest eflow installed.  
What does this stacktrace mean?

**Comment by fcabrera23** [comment]
@hooligan495,

Could you please try running `sudo iotedge check` and share the output?

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @hooligan495,

This issue seems to be related to the TPM EFLOWProxy and the KeepAliveTime from CoreServices. To modify this, check [ KeepAliveTime: Core Services | Microsoft Docs](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc782936(v=ws.10)) and reboot your machine so that the KeepAlive TCP detects the change and will kick in fast.

Could you please check this solution?

Thanks,
Franicsco

**Comment by fcabrera23** [comment]
Closed due to innactivty
